# Uncomment this file to enable multilanguage site support

[en]
    languageName = "English"
    languagedirection = "ltr"
    title = "Martin Liu's Blog"
    weight = 2
[zh-cn]
    languageName = "中文"
    languagedirection = "ltr"
    title = "Martin Liu's Blog"
    weight = 1
